# Generated by Django 3.2.5 on 2021-10-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='files',
            new_name='fileName',
        ),
    ]
