# Generated by Django 3.2.5 on 2021-10-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to='paper.Files'),
        ),
    ]
